# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Nirmal Mani
tagline:          'My development notes'
description:      'Passionate about solving engineering problems and learning new technologies'
url:              https://nirmal-mani.github.io
baseurl:          /

author:
  name:           'Nirmal Mani'
  url:            https://github.com/nirmal-mani

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nirmal-mani
